-- 코드를 입력하세요
SELECT
  R.REST_ID
  , R.REST_NAME
  , R.FOOD_TYPE
  , R.FAVORITES
  , R.ADDRESS
  , ROUND(AVG(V.REVIEW_SCORE),2) AS SCORE
FROM REST_INFO AS R
INNER JOIN REST_REVIEW AS V
ON R.REST_ID = V.REST_ID
WHERE R.ADDRESS REGEXP "^(서울)"
GROUP BY R.REST_NAME
ORDER BY SCORE DESC, FAVORITES DESC;